### PR TITLE
postgresql: Do not create db_maker role if it already exists

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by tboerger** [comment]
Please indent the code, it looks ugly :D
:+1:

**Comment by aspiers** [comment]
Agreed, indentation should not break it here :-)

**Comment by vuntz** [comment]
Isn't it standard to reset the indentation level when we use the `<< EOF` magic?

**Comment by tboerger** [comment]
> Isn't it standard to reset the indentation level when we use the << EOF magic?

Where do you get this from? I can not remember any other place where we do that.

**Comment by aspiers** [comment]
BTW http://stackoverflow.com/questions/3772864/how-do-i-remove-leading-whitespace-chars-from-ruby-heredoc might help here ... although in this case you don't need to avoid the indentation so you only need the hyphen: `<<-EOF`.

**Comment by mjura** [comment]
Ok, after adding indentation, if is it possible +1 from me

**Comment by vuntz** [comment]
So I don't really mind adding indentation, but looking at the bash resources we have in other cookbooks, that's also the most common style that is being used.

Anyway, force-pushed with updated indentation.

**Comment by tboerger** [comment]
:+1:

**Comment by rsalevsky** [comment]
:+1:

**Pull request merged**
